class LanguageService:
    @staticmethod
    def load_texts():
        return {
            "es": {
                "app_title": "YAGC - Escáner de archivos y directorios",
                "menu_bar1": "Idioma",
                "menu_bar2": "Ayuda",
                "language_menu1": "English",
                "language_menu2": "Español",
                "help_menu1": "Sobre",
                "tab1": "Análisis",
                "tab2": "Histórico",
                "tab3": "Actualizaciones",
                "tab4": "Config.",
                "button_label1": "Escanear un archivo",
                "button_label2": "Escanear un directorio",
                "button_label3": "Ver historial de escaneos",
                "button_label4": "Actualizar base de datos",
                "button_label5": "Guardar cambios",
                "changes_saved": "¡Cambios guardados!",

                "checkbox_label1": "Escanear también las subcarpetas",
                "checkbox_label2": "Eliminar amenazas encontradas",
                "checkbox_label3": "Sonar al encontrar amenazas",

                "config_options_label": "Que hacer con los archivos infectados:",
                "combox_label1": "No hacer nada",
                "combox_label2": "Mover a carpeta designada",
                "combox_label3": "Borrarlos",

                "warning_title": "Advertencia",
                "delete_disclaimer": "Cuidado: Eliminar archivos puede ser peligroso. Considerá usar la opción de mover. Los falsos positivos pueden provocar pérdidas de archivos importantes.",

                "version_label": "Versión de ClamAV: ",
                "database_label": "Versión de la base de datos: ",
                "exit_label": "Salir",
                "select_file": "Selecciona un archivo",
                "all_files": "Todos los archivos",
                "text_files": "Archivos de texto",
                "image_files": "Archivos de imagen",
                "select_directory": "Selecciona un directorio",
                "no_history_files": "No hay archivos de historial disponibles.",
                "history_title": "Historial de escaneos",
                "open_result": "Abrir resultado",
                "database_locked": "El proceso de actualización de la base de datos se gestiona automáticamente y se ejecuta en segundo plano. No es necesario invocarlo manualmente.",
                "database_update_error": "Error al actualizar la base de datos:",
                "database_updated": "La base de datos se actualizó correctamente.",
                "database_up_to_date": "La base de datos ya está actualizada y se gestiona automáticamente en segundo plano. No es necesario actualizarla manualmente.",
                "database_updated_on": "Base de datos actualizada el:",
                "current_date": "Fecha actual",
                "version_date": "Fecha de versión",
                "unexpected_version_format": "Formato de versión inesperado.",
                "version_fetch_error": "No se pudo obtener la versión de ClamAV.",
                "generic_error": "Error:",
                "loading_message": "Cargando, por favor espere...",
                "error_message": "Hubo un error. Por favor, intente nuevamente.",
                "about_message": "YAGC es una interfaz gráfica para el escaneo de archivos y directorios usando el motor ClamAV.",
                "scan": "Escaneando",
                "scan_complete": "Escaneo Completado",
                "stdout": "Salida estándar",
                "stderr": "Salida de error",
                "result_saved": "Resultado guardado en",
               
                "version": "Versión",
                "about": "YAGC es una interfaz gráfica de usuario (GUI) diseñada para facilitar el uso "
                "de ClamAV, un software antivirus de código abierto. Esta aplicación está inspirada en proyectos "
                "como ClamWin y ClamTk, y ofrece una experiencia más accesible y visual para los usuarios que desean "
                "realizar escaneos antivirus en sus sistemas de forma rápida y sencilla.",
                "about_title": "YAGC",
            },
            "en": {
                "app_title": "YAGC - File and Directory Scanner",
                "menu_bar1": "Language",
                "menu_bar2": "Help",
                "language_menu1": "English",
                "language_menu2": "Español",
                "help_menu1": "About",
                "tab1": "Analysis",
                "tab2": "History",
                "tab3": "Updates",
                "tab4": "Configuration",
                "button_label1": "Scan a file",
                "button_label2": "Scan a directory",
                "button_label3": "View scan history",
                "button_label4": "Update database",
                "button_label5": "Save changes",
                "changes_saved": "Changes saved!",
                "checkbox_label1": "Scan subfolders as well",
                "checkbox_label2": "Remove found threats",
                "checkbox_label3": "Sound alarm when threats are found",

                "combox_label1": "Do nothing",
                "combox_label2": "Move to designated folder",
                "combox_label3": "Delete them",
                "config_options_label": "What to do with infected files:",

                "warning_title": "Warning",
                "delete_disclaimer": "Warning: Deleting files can be dangerous. Consider using the move option. False positives can lead to loss of important files.",

                "version_label": "ClamAV Version: ",
                "database_label": "Database Version: ",
                "exit_label": "Exit",
                "select_file": "Select a file",
                "all_files": "All files",
                "text_files": "Text files",
                "image_files": "Image files",
                "select_directory": "Select a directory",
                "no_history_files": "No history files available.",
                "history_title": "Scan history",
                "open_result": "Open result",
                "database_locked": "The database update process is managed automatically and runs in the background. Manual invocation is not necessary.",
                "database_update_error": "Error updating the database:",
                "database_updated": "The database was updated successfully.",
                "database_up_to_date": "The database is already up to date and managed automatically in the background. Manual updates are not necessary.",
                "database_updated_on": "Database updated on:",
                "current_date": "Current date",
                "version_date": "Version date",
                "unexpected_version_format": "Unexpected version format.",
                "version_fetch_error": "Failed to fetch ClamAV version.",
                "generic_error": "Error:",
                "loading_message": "Loading, please wait...",
                "error_message": "An error occurred. Please try again.",
                "about_message": "YAGC is a graphical interface for scanning files and directories using the ClamAV engine.",
                "scan": "Scanning",
                "scan_complete": "Scan Complete",
                "stdout": "Standard output",
                "stderr": "Error output",
                "result_saved": "Result saved at",
              
                "version": "Version",
                "about": "YAGC (Yet Another GUI for ClamAV) is a graphical user interface designed to simplify the use of ClamAV, an open-source antivirus software. This application is inspired by projects such as ClamWin and ClamTk, and provides a more accessible and visual experience for users who wish to perform antivirus scans on their systems quickly and easily.",
                "about_title": "YAGC",
            }
        }
